"""second migration

Revision ID: a71304e95563
Revises: 755f96baac00
Create Date: 2021-08-21 15:35:54.989048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71304e95563'
down_revision = '755f96baac00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'update_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'done')
    op.drop_column('project', 'update_at')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
